### ISSUE TITLE
This block doesn't show up in the site editor

### ISSUE THREAD

**Issue by ajcampbell** [richtabor/post-modified-time-block#1]
I've installed this block as a plugin and activated it, but when I search for it in the site editor, it doesn't appear.

The reading-time block works fine as I downloaded the zip you provided. Originally, I installed it the way I installed this block, i.e. downloaded the git repository, then selected that zip file in Wordpress, then activated the plugin.

**Comment by richtabor** [comment]
Hey @ajcampbell, if you're downloading from this repo here directly you'll need to build the files by running `npm install` and then `npm run build`.

**Comment by ajcampbell** [comment]
Ah, didn't realise I needed to build it. It works fine now. Thanks for your help, and for these useful blocks you've provided.
